### ISSUE TITLE
Cleaning up unit tests

### ISSUE THREAD

**Issue by jpz** [chardet/chardet#104]
It would be good to get the build to be green.

Should we separate out the failing tests into a folder where we keep failing tests (e.g. files that are known not to don't dected correctly), but only run these tests _exceptionally_  - e.g. during development testing with a flag?  

They could be aspirational targets to detect successfully. :)

**Comment by dan-blanchard** [comment]
Partially fixed by d588407, which now skips the 5 known failures. Will add a bit to `.travis.yml` to make it run just those tests in separate builds that are allowed to fail, so we can see if we make progress.

**Comment by jpz** [comment]
Great to see the green in Travis. 👍
