### ISSUE TITLE
chardet 3.0.0/3.0.1 broken

### ISSUE THREAD

**Issue by ajaeger** [chardet/chardet#112]
From: 
http://logs.openstack.org/20/456120/1/check/gate-openstack-manuals-tox-checkniceness-ubuntu-xenial/3c6cd7d/console.html#_2017-04-12_10_00_56_238447

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 51: character maps to <undefined>

This happens with both chardet 3.0.0 and 3.0.1 - with chardet 2.3.0, this works just fine.

**Comment by cmurphy** [comment]
It looks like we had an invalid character in our docs, we were able to fix it: https://review.openstack.org/#/c/456263

It's still interesting that this came up, I'm curious what changed to cause this.

**Comment by dan-blanchard** [comment]
The predictions for chardet may change from version to version as we make improvements, so in this case the predicted encoding was not compatible with one of the characters in your doc. I've been considering adding a final check so it tries to decode the string with the predicted encoding and eliminates any that are invalid, but I have not gotten a chance to add that yet.

**Comment by sigmavirus24** [comment]
> I've been considering adding a final check so it tries to decode the string with the predicted encoding and eliminates any that are invalid, but I have not gotten a chance to add that yet.

I'd rather we didn't. Here are a few reasons why:

1. str.encode/str.decode can trigger imports. Delayed imports in a web application can cause deadlocks in acquiring the import lock on certain versions of Python. Requests already has had this problem and I'd rather not add it to chardet.

2. I believe we can return all of our most confident detections. We can provide an extra function to users to do this for them, but I don't think we should do it as part of `detect`.

**Comment by dan-blanchard** [comment]
> str.encode/str.decode can trigger imports. Delayed imports in a web application can cause deadlocks in acquiring the import lock on certain versions of Python. Requests already has had this problem and I'd rather not add it to chardet.

I know about the import triggering, but not the deadlocks. The tricky bit there though is that typically people are using chardet so that they can call `bytes.decode` and process the file, so they're going to end up importing the same thing anyway.

> I believe we can return all of our most confident detections. We can provide an extra function to users to do this for them, but I don't think we should do it as part of detect.

#111 was just opened yesterday to add exactly that. I just need to review it.
