### ISSUE TITLE
Release 3.0.3 lacks some commits

### ISSUE THREAD

**Issue by yegorich** [chardet/chardet#131]
chardet-3.0.3.tar.gz on PyPI lacks at least https://github.com/chardet/chardet/commit/b874c25b08edd6bdbdd70a439c6cd603d6830226 commit, that fixes pytest dependency issue. Can you confirm this?

When are you going to release 3.0.4?

**Comment by dan-blanchard** [comment]
`master` currently has some backward incompatible changes in it—only an issue for people who were really digging around in the guts of the probers, which is quite rare—so I was hoping to hold off on doing a release until I finished #99. That said, `master` is faster and has some worthwhile changes in it, so maybe it's worth just doing a 4.0 release with those changes and then 4.1 will have the retrained models.

**Comment by simonklb** [comment]
I fail to see the reason to include pytest in the dist. Why was it added?

**Comment by dan-blanchard** [comment]
To allow people to run `python setup.py test` and have that actually work you need to add `pytest_runner` to your `setup_requires`, but the latest recommendation is to do that conditionally. That's what #119 (and b874c25) fixed.

**Comment by yegorich** [comment]
@dan-blanchard when I download chardet-3.0.3.tar.gz from PyPI its setup.py doesn't handle pytest_runner dependency conditionally. Only master branch does. This issue prevents chardet to be updated in Buildroot.
See https://stackoverflow.com/questions/44375119/buildroot-installing-of-the-pytest-runner-package-fails#comment75753421_44375119

**Comment by dan-blanchard** [comment]
I will release a 3.0.4 release with the setup.py fix today.

**Comment by yegorich** [comment]
Thanks

**Comment by dan-blanchard** [comment]
[3.0.4](https://github.com/chardet/chardet/releases/tag/3.0.4) is now up on [PyPI](https://pypi.python.org/pypi/chardet).

**Comment by simonklb** [comment]
I urge you to use tox instead. But that's up to you.

**Comment by sigmavirus24** [comment]
@simonklb trying to convince downstream redistributors to use anything other than ancient APIs is a noble but futile quest.
