### ISSUE TITLE
Kill Python 2.6 (and maybe Python 3.3?)

### ISSUE THREAD

**Issue by adamn** [chardet/chardet#133]
Python 2.6 support can be removed for future releases.  No modern project uses 2.6 and also does library upgrades so it seems that it would be best to just stop testing 2.6 so that code can be written without 2.6 workarounds.

I would also advocate for 3.3 removal since 3.4 was released 3 years ago.  This helps keep things clean.

I'm happy to make a PR if there's agreement on removing these versions from the tests/setup.

**Comment by dan-blanchard** [comment]
You'll hear no objections from me about removing 2.6 support. In a couple years we're going to want to make this Python 3 only anyway, since 2.7 EOL is 2020.
