### ISSUE TITLE
pypi chardet contains .pyc files

### ISSUE THREAD

**Issue by arnaudmorin** [chardet/chardet#139]
Hey guys,
As I have no idea where to ask, I ended up creating an issue here, sorry if it's the wrong place.

I am trying to automate the creation of debian package from pypi tarball sources: 

    https://pypi.python.org/pypi/chardet#downloads

but unfortunately, my system won't work until the .pyc files from the source tarball are removed:

    $ find . -name '*.pyc'
    ./tests/__pycache__/__init__.cpython-35.pyc
    ./tests/__pycache__/test_chardet.cpython-35-PYTEST.pyc

I can patch on my side after downloading the tarball, but I am wondering if the source should contain any .pyc file at all.

please advise

**Comment by arnaudmorin** [comment]
ping

**Comment by dan-blanchard** [comment]
I've updated our `MANIFEST.in` file to make sure those are not included, so this will be fixed in the next release.

**Comment by arnaudmorin** [comment]
amazing!
