### ISSUE TITLE
"high-level" CHANGELOG would be highly appreciated

### ISSUE THREAD

**Issue by yarikoptic** [chardet/chardet#147]
wanted to see what has changed since 2.3.0 since observing too high of a confidence where should be not so and was not sure if any changes since 2.3.0 could be attributed to fixed behavior.
Thanks in advance!

**Comment by dan-blanchard** [comment]
https://github.com/chardet/chardet/releases

**Comment by yarikoptic** [comment]
Coolio, thanks! 

1c: Let's hope that github never dies, or otherwise that knowledge would get largely lost. That could be prevented if it was also contained within some file within repository. FWIW -- shipping that file within source distribution also helps maintainers (like in Debian) to provide it whenever package is installed so users could find it in a conventional place without trying to figure out where it could potentially reside.
