### ISSUE TITLE
Compatiblity issues when running on Python 3.6 on iOS 

### ISSUE THREAD

**Issue by cclauss** [chardet/chardet#156]
* https://github.com/omz/Pythonista-Issues/issues/554
* https://github.com/aio-libs/aiohttp/issues/3135

There are occasional "no module named 'universaldetector'" messages that arise when chardet is installed as part of an aiohttp installation on [Pythonista](http://omz-software.com/pythonista) on iOS.  Does anyone know an effective workaround for this issue?

**Comment by sigmavirus24** [comment]
If one of the files in the module is missing (see: https://github.com/chardet/chardet/blob/master/chardet/universaldetector.py) then I'm not sure how this is a potential chardet problem. It sounds like an issue installing on iOS with either Pythonista or whatever tool is doing the installation.
