### ISSUE TITLE
clarify Trove license classifier

### ISSUE THREAD

**Issue by glyph** [chardet/chardet#162]
LGPL2 and LGPL3 have substantially different terms; right now setup.py specifies 

> License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)

but this is vague, since it doesn't actually tell you what terms are required.  (IMHO it shouldn't really be a trove classifier, since it doesn't *mean* anything)

Based on the dates involved, and the presence of the LGPL2.1 at the root of the repo, you probably want

> License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)

since I couldn't find the phrase "or any later version" anywhere in the codebase; if that ever did appear somewhere in something mark wrote, then you'd want

> License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)

**Comment by musicinmybrain** [comment]
See #255.

All the source file header comments have:

```
# version 2.1 of the License, or (at your option) any later version.
```

…so LGPLv2+ appears to be the correct license.
