### ISSUE TITLE
Offering to help with the project

### ISSUE THREAD

**Issue by skorokithakis** [chardet/chardet#169]
I've noticed that activity on this project has slowed, and I was wondering if you needed some help. Would you consider adding the project to [Code Shelter](https://www.codeshelter.co/)? It's an open community of open source maintainers (please feel free to join!) that aims to help OSS projects out (fixing bugs, merging PRs, releasing, etc), and I'm a member and can help.

You can [read more details about it](https://www.codeshelter.co/faq/) or [add your project](https://www.codeshelter.co/projects/add/) to it.

**Comment by sigmavirus24** [comment]
> I've noticed that activity on this project has slowed,

Why is this a problem? The project is relatively stable. Activity for activity's sake is bad and will lead to destabilization.

**Comment by skorokithakis** [comment]
I don't know, I saw PRs open (including one for a pending release) and thought you might need help. Just ignore me if that's not the case, thanks.

**Comment by dan-blanchard** [comment]
Thanks for offering to help. I have not have had time to work on chardet in quite some time (as I'm sure is evident). There's also the fact that [cChardet](https://github.com/PyYoshi/cChardet) is better for like 95% of our users. It's faster, more accurate, supports more encodings, and is more actively maintained. We've talked about trying to maybe combine efforts in #19, but I haven't made a move on that.

The main reason I see for chardet's continuing existence is for Python platforms on which cChardet is not supported (namely Jython).

**Comment by skorokithakis** [comment]
Oh, I didn't know about cchardet, thanks. I use chardet everywhere, but I'll switched to that, thanks (the offer to help still stands if you need it, on this or any other project).

**Comment by skorokithakis** [comment]
The offer to join the community still stands, too!
