### ISSUE TITLE
LICENSE file missing from latest PyPI Release

### ISSUE THREAD

**Issue by johnthagen** [chardet/chardet#199]
Tools such as [`pip-licenses`](https://github.com/raimon49/pip-licenses) use the LICENSE file included in uploaded Python packages to generate license reports. The latest release of `chardet` does not have a LICENSE file included which makes it more challenging to comply with the LGPL license.

Could a new release of chardet be released using the latest `wheel` library that pulls in the LICENSE file automatically (#182)?

**Comment by dan-blanchard** [comment]
chardet 4.0.0 includes the `LICENSE` file
