### ISSUE TITLE
Turkish (iso-8859-9) detecting.

### ISSUE THREAD

**Issue by queeup** [chardet/chardet#20]
I want to help for Turkish language detection but I don't understand what order or how I supposed to put things to lang*model.py.

Turkish is Latin5 8-bit single-byte coded Language
http://en.wikipedia.org/wiki/ISO-8859-9
http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-128.pdf (code table is on page 16)

**Comment by dan-blanchard** [comment]
Fixed by #41.
