### ISSUE TITLE
CharSetGroupProber always returns ProbingState.DETECTING?

### ISSUE THREAD

**Issue by flying-sheep** [chardet/chardet#202]
It seems like there’s no shortcut handling in Universal detector, is that intended?

The Universal detector shortcuts if a probers’ `feed` returns `ProbingState.FOUND_IT`:

https://github.com/chardet/chardet/blob/1db03470dd5b82fb305b5fd1bebfb46cd961551f/chardet/universaldetector.py#L210-L212

But `CharSetGroupProber`s will never set `self._state = ProbingState.FOUND_IT`, so it will at most return `ProbingState.DETECTING`:

https://github.com/chardet/chardet/blob/1db03470dd5b82fb305b5fd1bebfb46cd961551f/chardet/charsetgroupprober.py#L74-L76

So the `MBCSGroupProber` asks the `UTF8Prober`, which replies `FOUND_IT`, then the `MBCSGroupProber` sets it as `_best_guess_prober` and returns `DETECTING`. There’s no win state, `CharSetGroupProber`s will never say they found anything, right?

But that’s probably intended as the universal detector compares the confidence in `close`...

**Comment by dan-blanchard** [comment]
That's a really interesting point. I think you may be right that that's a bug.

It's always been my understanding that `FOUND_IT` is for when we are completely certain of the encoding, so if an individual prober is certain, I'm not sure why the group prober that it is contained inside wouldn't also be certain.
