### ISSUE TITLE
Unable to install older versions of chardet with latest python images

### ISSUE THREAD

**Issue by anu-kailash** [chardet/chardet#211]
> ERROR: Could not find a version that satisfies the requirement chardet<4,>=3.0.2 (from requests)
> ERROR: No matching distribution found for chardet<4,>=3.0.2

With latest versions of pip there is a problem pulling older versions of chardet.

Steps to reproduce:

> $ docker run -it python:3.8-slim-buster bash
> root@17652c597f2b:/# pip install -i https://pypi.org/pypi/ chardet==3.0.2
> Looking in indexes: https://pypi.org/pypi/
> ERROR: Could not find a version that satisfies the requirement chardet==3.0.2
> ERROR: No matching distribution found for chardet==3.0.2
> root@17652c597f2b:/# 

Seems related to #199 and the latest updates made to pip

**Comment by dan-blanchard** [comment]
Your command is wrong. You either don't want to specify the index URL at all (in which case it will use `https://pypi.org/simple/` anyway), or you need to specify the correct URL like in `pip install -i https://pypi.org/simple/ chardet==3.0.2`
