### ISSUE TITLE
LICENSE file not included in pip package metadata files

### ISSUE THREAD

**Issue by darkdragon-001** [chardet/chardet#217]
LICENSE file should be included in and installed with the wheel pip package.

**Comment by domdfcoding** [comment]
The LICENSE file is in the `.dist-info` directory of the wheel for the latest release, as can be seen at https://www.wheelodex.org/projects/chardet/

**Comment by hugovk** [comment]
Confirmed by downloading `chardet-4.0.0-py2.py3-none-any.whl ` from https://pypi.org/project/chardet/4.0.0/#files and renaming to a `.zip` and extracting. `LICENSE` is in `chardet-4.0.0.dist-info/`.

**Comment by darkdragon-001** [comment]
I can confirm it is there since `4.0.0`.
