### ISSUE TITLE
Predicted encoding unable to decode given string

### ISSUE THREAD

**Issue by KSneijders** [chardet/chardet#242]
Reproduce by using: 

```py
import chardet

text = 'latin-1 encoded string > éáû'.encode('ISO-8859-1')  # latin-1

charset = chardet.detect(text)
# charset = {'encoding': 'windows-1255', 'confidence': 0.99, 'language': 'Hebrew'}

print(text.decode(charset['encoding']))
# UnicodeDecodeError: 'charmap' codec can't decode byte 0xfb in position 27
```

Not sure why it's considered Hebrew

**Comment by dan-blanchard** [comment]
Chardet does not work reliably on short strings, as it's all about statistics. The models all work on the assumption that the data they're given is natural language and not a contrived example. "éáû" is not a sequence that is going to happen in any language I am aware of.

That said, it is frustrating when chardet yields a result that cannot actually decode the input string, and that's something I would like to improve upon.

**Comment by KSneijders** [comment]
Thanks for the quick response! That makes sense. It'd be nice if chardet could take the actual decoding into consideration. 

It's a great library, and I can see it working pretty well on larger strings, unfortunatelt I also work with a lot of small strings that don't necessarily have to have the same decoding. 

I'll keep an eye out, for a possible update!
