### ISSUE TITLE
Dependency warning (v5.0.0)

### ISSUE THREAD

**Issue by drfunjohn** [chardet/chardet#263]
RobotFramework does not use urllib and chardet library directly(no user libraries that uses "chardet")
When tests started next error appears:

`/usr/local/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(`
  
  If install chardet==4.0.0 this warning does not appears.
  
I'm not sure who exactly generates this warning because warning are truncated. This warning are not affect at execution of tests but execution itself are failed, test reports are not generated.

**Comment by dan-blanchard** [comment]
This is a requests issue, no a chardet one.
