### ISSUE TITLE
Is the license LGPL v2.1 or later or just LGPLv2.1 only?

### ISSUE THREAD

**Issue by ghost** [chardet/chardet#269]

**Comment by mxmehl** [comment]
I have the same question. It would be great to clearly define this, and also provide a valid SPDX license identifier. It could be `LGPL-2.1-only` or `LGPL-2.1-or-later`. The current information is ambiguous.

If the maintainers/core contributors could confirm whether they licensed this nice piece of software ONLY under this license or are also willing that people use it under newer versions of the LGPL (like LGPL-3.0 or any future versions), I'd be happy to propose the necessary changes to make it clear in the package's metadata.

**Comment by stefan6419846** [comment]
According to #162, it seems to be `LGPL-2.1-or-later`.

**Comment by dan-blanchard** [comment]
Yeah, this was addressed in #255 which fixed #162.
