### ISSUE TITLE
Allow running of the package via `python3 -m chardet ...`

### ISSUE THREAD

**Issue by DeflateAwning** [chardet/chardet#272]
I want to be able to execute the `chardet` main script (packaged as an executable) by running `python3 -m chardet ...`. Currently it doesn't work. Would be great if it did work.

**Comment by dan-blanchard** [comment]
Added in 0e9b7bc20366163efcc221281201baff4100fe19 and it'll be in the next release

**Comment by DeflateAwning** [comment]
Can you please release this?

**Comment by dan-blanchard** [comment]
Released!

**Comment by DeflateAwning** [comment]
Thank you!
