### ISSUE TITLE
Next release for Python 3.11

### ISSUE THREAD

**Issue by wbarnha** [chardet/chardet#275]
Hi there, we use `chardet` in https://github.com/faust-streaming/faust and we'd like to see a release made for Python 3.11 soon. Any timeline on when that'll happen? I see that https://github.com/chardet/chardet/commit/72642823f7bd4b12efe9fa066ec7a84c607e141f has been merged in, so we could run `pip install 'chardet @ git+https://github.com/chardet/chardet'` in the meantime.

**Comment by dan-blanchard** [comment]
https://github.com/chardet/chardet/releases/tag/5.1.0
