### ISSUE TITLE
"~{" is recognized as an ESCAPE character

### ISSUE THREAD

**Issue by netbuddy** [chardet/chardet#290]
My text body contains a string like "xxx~{xxx", and the result of text encoding recognition is "unknown". Why is "xxx~{xxx" recognized as the ESCAPE character in the regular expression 'ESC_DETECTOR = re.compile(b"(033|~{)")'?Thank you.

**Comment by dan-blanchard** [comment]
It's because `~{` sequences are used to indicate escapes in [HZ character encodings](https://en.wikipedia.org/wiki/HZ_(character_encoding)).
