### ISSUE TITLE
Is chardet 4.0.0 release is End of life?

### ISSUE THREAD

**Issue by yogi345** [chardet/chardet#297]
Hello folks,

I would like to know "chardet 4.0.0" is end of life? If there are any issues found with this release, will those patched in this release?

Thanks,

**Comment by dan-blanchard** [comment]
No, it's not EOL. I just don't have a ton of time to dedicate to it lately. Most of the open issues are from people running it with entirely too little data, and then being surprised by the result. chardet uses statistical models to determine the encoding, so less data will always result in worse results. Are there issues you are currently encountering?

**Comment by yogi345** [comment]
Thanks Dan for your response. One of our products using chardet 4.0.0 but
since there is not much content getting committed to this version our
security scans are showing warnings to upgrade it to the latest version.
Hence I put this question.
