### ISSUE TITLE
Upgrading from oldish version

### ISSUE THREAD

**Issue by johnraz** [chardet/chardet#54]
Hi guys,

I recently took over a project that make use of chardet @ 73ab96363edcad26a9f59e240c0c073a34ba4f88 which I guess is 1.1.

Do you have any pointer on big breaking changes since then I should be aware of?

Thx !

**Comment by dan-blanchard** [comment]
I don't believe there are any API breaking changes, but until we cut a new release, be aware that there are some known problems with detecting Latin-1/CP1252.

**Comment by johnraz** [comment]
Awesome @dan-blanchard , thanks a lot for the quick response !
