### ISSUE TITLE
Issue with invoking chardet with IronPython: 'Expected a bytes object, not an unicode object'

### ISSUE THREAD

**Issue by dxtodorovic** [chardet/chardet#56]
Due to the way IronPython 2.7.5 natively handles strings, I'm encountering errors with passing arguments to chardet's \_\_init\_\_ in third-party packages using chardet (requests for example).

Specifically, this section of code causes problematic behaviour:

    def detect(byte_str):
        if (PY2 and isinstance(byte_str, unicode)) or (PY3 and
                                                   not isinstance(byte_str,
                                                                  bytes)):
            raise ValueError('Expected a bytes object, not a unicode object')

Can we perhaps add some way of detecting if we're using IronPython and then a check in \_\_init\_\_, which would pass bytes(string) to u.feed() instead?

For instance, in compat.py:

    import platform

    if (platform.python_implementation() == 'IronPython'):
        IPY = True
    else:
        IPY = False

in \_\_init\_\_.py:

    from compat import IPY
    if (PY2 and not IPY and isinstance(byte_str, unicode)) or (PY3 or IPY and not isinstance(byte_str, bytes)):
        raise ValueError('Expected a bytes object, not a unicode object')

**Comment by sigmavirus24** [comment]
If the string we're given isn't a byte string, then we have to encode it. However we choose to encode it will bias the detector. We need a raw byte string to give you accurate results. Can you explain what you were doing in requests such that `chardet.detect` received anything other than a bytestring?

**Comment by animenon** [comment]
I get this while invoking chardet from a python3.4 :

Traceback (most recent call last):
  File "C:\xyz\detectChar.py", line 3, in <module>
    result = chardet.detect(rawdata)
  File "C:\Python34\lib\site-packages\chardet\__init__.py", line 25, in detect
    raise ValueError('Expected a bytes object, not a unicode object')
ValueError: Expected a bytes object, not a unicode object

**Comment by dan-blanchard** [comment]
@animenon Is this just standard Python 3.4? If so, then you probably passed a `str` object (what `unicode` became in Python 3) instead of a `bytes` object to chardet.  Make sure that any files you're reading are being opened with `mode` set to `'rb'` so that you'll get `bytes` instead of `str`.

**Comment by animenon** [comment]
@dan-blanchard  Thank you.
