### ISSUE TITLE
Chardet returns ISO-8859 when cp1252 is better

### ISSUE THREAD

**Issue by mlissner** [chardet/chardet#59]
Ages ago, [I filed a bug that got erroneously closed by a commit][1]. I just stumbled on it again today, so I'm moving it over from the old location so we can see about getting it going again. 

Here's the text of the old bug:

> I had a frustrating issue recently when trying to use chardet to work with a web page: http://stackoverflow.com/questions/11588458/how-to-handle-encodings-using-python-requests-library

> My solution was to write a bit of custom code that says, "Whenever chardet reports ISO-8859-1, instead use cp1252." It would be great if chardet internalized this behavior.

> Basically, browsers don't use a number of character encodings, and instead map to other ones instead. Since most of the data that chardet is used on will be coming from the web, it makes sense for it to return the character encodings that are used by browsers. 

> This might make sense as an option rather than default functionality....not sure, but I'd love to see this be added.

Is there still an appetite for this kind of an issue? Basically, I think&mdash;and ages ago, committer @dan-blanchard agreed&mdash;that chardet should never return ISO-8859 and should always return cp1252 instead.

[1]: https://github.com/dcramer/chardet/issues/8

**Comment by dan-blanchard** [comment]
chardet currently does this.  We never return ISO-8859-1, and instead always say Windows-1252 (aka cp1252).  The Latin1Prober code is [here](https://github.com/chardet/chardet/blob/master/chardet/latin1prober.py) if you're curious.

**Comment by mlissner** [comment]
Oh, that's excellent, thank you! Glad to have closed the loop!
