### ISSUE TITLE
get wrong codec

### ISSUE THREAD

**Issue by asdfsx** [chardet/chardet#60]
I use chardet to detect the codec of the 'Cinecitt%C3%A0%20Make', like this
```python
import urlparse
import chardet
a = 'Cinecitt%C3%A0%20Make'
b = urlparse.unquote(a)
chardet.detect(b)
```

the result is {'confidence': 0.814286076190637, 'encoding': 'ISO-8859-2'}
but '%c3%a0' is an utf8 code of character 'à'
is there something wrong?

**Comment by asdfsx** [comment]
find the problem 
In 2.3.0, in SBCSGroupProber, the Latin2HungarianModel is still in use. And I think there may be sth wrong within the 'iso-8859-2' charset map.
In latest version, the Latin2HungarianModel has been disabled, so the result is "uff-8"

And I found , in uchardet, in nsSBCSGroupProber.cpp, Latin2HungarianModel is also disabled:
``` c
// disable latin2 before latin1 is available, otherwise all latin1
// will be detected as latin2 because of their similarity. 
// mProbers[10] = new nsSingleByteCharSetProber(&Latin2HungarianModel);
// mProbers[11] = new nsSingleByteCharSetProber(&Win1250HungarianModel);  
```

**Comment by dan-blanchard** [comment]
Sorry, I know I'm really behind on putting out a release with this fix in it.
