### ISSUE TITLE
failed to detect utf8 "FAHR•WERK"

### ISSUE THREAD

**Issue by asdfsx** [chardet/chardet#61]
I got the original codec from url "FAHR%E2%80%A2WERK", it's "FAHR•WERK" in utf-8.
But when I use chardet.detect, the result is {'confidence': 0.73, 'encoding': 'windows-1252'}
and the confidence of the utf-8 is only 0.505.
And I think there's sth wrong with utf8prober. So I look into utf8prober.py, and find code below:

``` python
elif coding_state == MachineState.start:
    if self.coding_sm.get_current_charlen() >= 2:
        self._num_mb_chars += 1
```

It seems only multibyte character can be judged as an utf-8 character.
So codec like "FAHR%E2%80%A2WERK" get a very low confidence.

In this case , I think we should judge the the single byte character also as an utf-8 character.
So I change the code into:

``` python
elif coding_state == MachineState.start:
    if self.coding_sm.get_current_charlen() >= 1:
        self._num_mb_chars += 1
```

and the result is {'confidence': 0.99, 'encoding': 'utf-8'}

**Comment by asdfsx** [comment]
maybe this can also solve the problem, I mentioned before, #60

**Comment by asdfsx** [comment]
any response???about this issue???@dan-blanchard

**Comment by dan-blanchard** [comment]
Since chardet uses statistics to determine encodings, it has poor performance for short strings.  

Also, we must only rely on multi-byte characters for determining if a string is UTF-8 because we want to be able to detect single-byte encodings like ASCII and Windows-1252.

Could you please explain what exactly you're trying to use chardet for and how you're calling it?  Did you run `chardet.detect(b'FAHR%E2%80%A2WERK')`?

**Comment by asdfsx** [comment]
No, I run somethink like this
```python
import urlparse
import chardet
a = 'FAHR%E2%80%A2WERK'
b = urlparse.unquote(a)
chardet.detect(b)
```
I use it mainly for detect short character's, such as website's title.
In china, japan or somewhere else, website use not only utf-8 but also gbk, shift-jis, etc. So I need to detect what kind of character the title is, then translate them into utf-8. And people sometime likes to add some special symbols into the title like '★'，'•'. These thing may make the detecting failed.

**Comment by sils** [comment]
Have a similar problem, running chardet on a simple python file containing umlauts which reads totally fine when just using utf-8, but chardet detects `iso-8859-2`. Here's our code: https://gitlab.com/coala/coala-utils/commit/d5b707689a150d1c561d3fa0912e5d1cb79f0441#59e25ab47f5113468cf960272779acd36dcfb680_0_38 which fails the test

**Comment by dan-blanchard** [comment]
chardet is inaccurate for short strings, as has been stated many times. Being able to restrict the encoding set  as suggested in #70 would go a long way to fixing some of these common issues, so I will prioritize adding that in the next version.
