### ISSUE TITLE
ASCII escape control character prevents detection of encoding

### ISSUE THREAD

**Issue by DRMacIver** [chardet/chardet#63]
It appears to be the case that the presence of '\x1b' character (the escape key) in an ascii string prevents it from being recognised as ascii. e.g. for any n the following returns an encoding of None:

```python
b'0' * n + b'\x1b'
```

This behaviour is present in master at ff1d9173dc4304899d6aa982d3a12f171a82da1c

**Comment by dan-blanchard** [comment]
Great find. That one probably has been around for a while!
