### ISSUE TITLE
Escape control character also prevents detection in utf-8 

### ISSUE THREAD

**Issue by DRMacIver** [chardet/chardet#65]
The following has no encoding detected:

``` python
u'\u020d\x1b'.encode('utf-8')
```

Again, not a length issue. Padding with ascii doesn't change anything. The initial character _is_ needed, I believe purely because it prevents the fix in #63 from applying by preventing the string from being considered as ascii.

Behaviour is present in 9e419e9b411a15e26c5542968b6daa3fbb4c672d

**Comment by DRMacIver** [comment]
PS. If these are annoying you and you don't care, just let me know and I'll stop.

**Comment by dan-blanchard** [comment]
Thanks for reporting this, but you can always artificially come up with something that breaks chardet, but we only really care if it works on real world data, so I'm going to close this. We will only return a non `None` result when one of our encoding detectors reaches a minimum threshold, and that's part of the API.
