### ISSUE TITLE
Misdetection of utf-8 as ISO-8859-2 for german umlauts

### ISSUE THREAD

**Issue by ruefo** [chardet/chardet#75]
Version: chardetect-script.py 2.3.0 on Windows environment; Python 3.4.3 (native) and in Cygwin shell (same in other shells)
Here the content of the misdetected script:
```
#!/usr/bin/env python3
# coding: utf-8
#
################################################################################

__version__ = '1.0'
__author__ = 'ü'
```
output of chardet:
```
$ chardetect uu.py 
uu.py: ISO-8859-2 with confidence 0.7916670185186749
```
output of file (Cygwin):
```
$ file uu.py 
uu.py: a /usr/bin/env python3 script, UTF-8 Unicode text executable, with CRLF line terminators
```
If i read the problematic line by `open(file, 'rb').readlines()` i get 
`b"__author__ = '\xc3\xbc'\r\n"`

Am i getting something wrong?

**Comment by dan-blanchard** [comment]
Unfortunately, it's an artifact of having to rely on statistical models to detect encodings.  Sometimes we're wrong because there's not enough evidence.  One character with an umlaut doesn't give us much to go on.  If you know you're going to be processing things like Python source files that might have a header that actually tells you the encoding, that's the better thing to rely on.

**Comment by ruefo** [comment]
Thanks for the reply. OK, i understand. I just have been wondering why `file` gets it correctly.

**Comment by dan-blanchard** [comment]
`file` probably just has models that are biased toward UTF-8.  It's also possible it checks for headers.  I'm not sure the exact algorithm uses, but it can detect far fewer encodings than we can.

**Comment by Tronic** [comment]
Valid UTF-8 sequences (w or w/o BOM) as well as any Unicode sequence with BOM should always take precedence over 8-bit encodings. Unfortunately I'm getting more failures than correct detections from chardet, and often an encoding that cannot even be decoded is reported. I was forced to write my own function that, despite being simple, performs much better. https://paste.zi.fi/p/decode.py/view
