### ISSUE TITLE
Is it OK to replace GB2312 by GB18030?

### ISSUE THREAD

**Issue by fyrestone** [chardet/chardet#79]
From wiki:
Like UTF-8, GB18030 is a superset of ASCII and can represent the whole range of Unicode code points; in addition, it is also a superset of GB2312.

If GB18030 is a superset of GB2312, is it OK to replace GB2312 by GB18030?

**Comment by dan-blanchard** [comment]
Check out the discussion on the closed pull request #33  for why we're not doing that.
