### ISSUE TITLE
Please do not remove old versions from pypi

### ISSUE THREAD

**Issue by khink** [chardet/chardet#86]
Hi,

I notice that older versions (pre-2.3.0) have been removed from https://pypi.python.org/pypi/chardet 

Removing older versions will break people's deployments. Could you please keep this in mind when making new releases?

Thanks in advance,

Kees

**Comment by dan-blanchard** [comment]
They're still available from via pip.  They're just hidden:

![](https://www.dropbox.com/s/knkntkv7dvk1480/Screenshot%202016-04-04%2008.35.13.png?dl=1)

I think it's the new default on PyPI:

![](https://www.dropbox.com/s/uksyz1gh1j528fw/Screenshot%202016-04-04%2008.36.08.png?dl=1)

**Comment by khink** [comment]
I did not know that. Thanks for explaining!
