### ISSUE TITLE
ISO-8859-1 not mentioned in documentation

### ISSUE THREAD

**Issue by rrthomas** [chardet/chardet#88]
I presume this is because it's covered by Windows 1252, but whereas other ISO-8859 encodings are mentioned next to their Windows superset, ISO-8859-1 is not.

If in fact the issue is more subtle, that would also be worth documenting!

**Comment by sigmavirus24** [comment]
I don't believe it's more subtle. Care to send a PR updating the documentation?

**Comment by rrthomas** [comment]
See PR #89.
