### ISSUE TITLE
Line Feed

### ISSUE THREAD

**Issue by damon-atkins** [chardet/chardet#91]
Hi Guys,
   Does this return information about the line feed of a file e.g.
LF+CR
LF
CR
CR+LF

**Comment by sigmavirus24** [comment]
@damon-atkins I don't understand your question.

**Comment by dan-blanchard** [comment]
chardet only returns what it believes to be the encoding for an arbitrary set of bytes. It doesn't output anything about line endings the way the `file` UNIX command does.

**Comment by damon-atkins** [comment]
You can close this if its not a plan enhancement, you would look at..
