### ISSUE TITLE
detect wrong ON windows 

### ISSUE THREAD

**Issue by rhinoceros** [chardet/chardet#93]
python 2.7.11
chardet 2.3.0
cchardet-1.1.1-cp27-cp27m-win_amd64.whl (md5)
window server 2008 r2 enterprise
system language: chinese simple (操作系统显示语言：简体中文）
test.py is the python code
testfile.cs is the input file (open by notepad, [save as（另存） ] show the encode（编码） is ANSI
testfile.chardet.cs is the output file: decode by chardet.detect(raw)['encoding'] ,then , encode by utf8
testfile.cchardet.cs is the output file: decode by cchardet.detect(raw)['encoding'] ,then , encode by utf8
testfile.GB2312.cs is the output file: decode by 'GB2312' ,then , encode by utf8.

testfile.GB2312.cs is the RIGHT.
[test_chardet.zip](https://github.com/chardet/chardet/files/579817/test_chardet.zip)

**Comment by flashlxy** [comment]
ANSI可以说不是一种编码，它是随操作系统变化的， 基本上会被detect成欧洲那边的编码，信度值会很低，这时候我们应该取系统默认编码。
