### ISSUE TITLE
GB18030 for Chinese

### ISSUE THREAD

**Issue by atbest** [chardet/chardet#94]
I just check the source code from [upstream](https://hg.mozilla.org/mozilla-central/file/bc7deafdac4b/extensions/universalchardet/src/base/nsGB2312Prober.h). They commented clearly that `We use gb18030 to replace gb2312, because 18030 is a superset.` If the upstream already corrected this problem, there is no reason to hold the problem here. Please reopen and merge [33](https://github.com/chardet/chardet/pull/33). It's funny to write the following code.
```
if encoding == 'GB2312':
    encoding = 'GB18030'
```

**Comment by qwIvan** [comment]
same problem

**Comment by softwarevamp** [comment]
should distinguish GB2312 / GBK / GB18030.

**Comment by x1angli** [comment]
It seems that the original author of chardet is unwilling to make the gb18030 change, nor distinguishing between gb18030 and gb2312, so I fored a separate repo: https://github.com/x1angli/chardet
hope it helps 
@atbest @softwarevamp

**Comment by dan-blanchard** [comment]
I'm adding a `should_rename_legacy` flag in #264 that does not go as far as treating `gb2312` as `gb18030`, but it does return `gbk` instead of `gb2312` if you enable the flag. 

If someone would like to provide us with a proper gb18030 prober, we're always open to contributions.
